import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const APIS = [
  {
    key: "list_models",
    name: "Listar modelos IA",
    description: "Devuelve todos los modelos de IA configurados en la plataforma.",
    module: "configuracion",
    submodule: "modelos_ia",
    category: "internal",
    method: "GET",
    path: "/api/config/models",
    authType: "none",
    docs: JSON.stringify({
      params: [],
      request: null,
      response: [
        { id: "cmr123", name: "Qwen Local", provider: "ollama", modelPath: "qwen2.5:32b", active: true },
      ],
    }),
  },
  {
    key: "create_model",
    name: "Crear modelo IA",
    description: "Registra una nueva configuración de modelo IA.",
    module: "configuracion",
    submodule: "modelos_ia",
    category: "internal",
    method: "POST",
    path: "/api/config/models",
    authType: "none",
    docs: JSON.stringify({
      params: [
        { name: "name", type: "string", required: true, desc: "Nombre visible del modelo" },
        { name: "provider", type: "ollama | openai | mock", required: true },
        { name: "modelPath", type: "string", required: true, desc: "ID del modelo en el proveedor" },
        { name: "baseUrl", type: "string", required: false, desc: "URL del servicio (Ollama)" },
        { name: "apiKey", type: "string", required: false, desc: "Requerido para OpenAI" },
        { name: "scope", type: "local | cloud", required: false, default: "local" },
        { name: "config", type: "JSON", required: false, desc: "temperature, top_p, max_tokens, systemPrompt" },
      ],
      request: {
        name: "Qwen Local",
        provider: "ollama",
        modelPath: "qwen2.5:32b",
        baseUrl: "http://localhost:11434",
        scope: "local",
        config: JSON.stringify({ temperature: 0.2, top_p: 0.9, max_tokens: 1024, systemPrompt: "Eres un experto legal colombiano." }),
      },
      response: { id: "cmr123", name: "Qwen Local", provider: "ollama", active: false },
    }),
  },
  {
    key: "update_model",
    name: "Actualizar modelo IA",
    description: "Modifica una configuración de modelo IA existente.",
    module: "configuracion",
    submodule: "modelos_ia",
    category: "internal",
    method: "PUT",
    path: "/api/config/models/{id}",
    authType: "none",
    docs: JSON.stringify({
      params: [{ name: "id", type: "string", in: "path", required: true }],
      request: { active: true },
      response: { id: "cmr123", name: "Qwen Local", active: true },
    }),
  },
  {
    key: "delete_model",
    name: "Eliminar modelo IA",
    description: "Elimina una configuración de modelo IA.",
    module: "configuracion",
    submodule: "modelos_ia",
    category: "internal",
    method: "DELETE",
    path: "/api/config/models/{id}",
    authType: "none",
    docs: JSON.stringify({
      params: [{ name: "id", type: "string", in: "path", required: true }],
      request: null,
      response: { id: "cmr123", deleted: true },
    }),
  },
  {
    key: "test_model",
    name: "Testear modelo IA",
    description: "Envía un prompt de prueba a un modelo IA y devuelve la respuesta cruda.",
    module: "configuracion",
    submodule: "modelos_ia",
    category: "internal",
    method: "POST",
    path: "/api/config/models/test",
    authType: "none",
    docs: JSON.stringify({
      params: [{ name: "id", type: "string", in: "body", required: true, desc: "ID del modelo a probar" }],
      request: { id: "cmr123" },
      response: { ok: true, text: "...", rawText: "...", latencyMs: 200, usage: { prompt_tokens: 100, completion_tokens: 50, total_tokens: 150 } },
    }),
  },
  {
    key: "discover_models",
    name: "Descubrir modelos locales",
    description: "Lista modelos disponibles en una instancia Ollama.",
    module: "configuracion",
    submodule: "modelos_ia",
    category: "internal",
    method: "GET",
    path: "/api/config/models/discover?baseUrl={baseUrl}",
    authType: "none",
    docs: JSON.stringify({
      params: [{ name: "baseUrl", type: "string", in: "query", required: false, default: "http://localhost:11434" }],
      request: null,
      response: { models: [{ name: "qwen2.5:32b", model: "qwen2.5:32b", parameter_size: "32B" }] },
    }),
  },
  {
    key: "list_apis",
    name: "Listar APIs",
    description: "Devuelve el catálogo de APIs disponibles para el agente.",
    module: "configuracion",
    submodule: "apis",
    category: "internal",
    method: "GET",
    path: "/api/config/apis",
    authType: "none",
    docs: JSON.stringify({
      params: [],
      request: null,
      response: [{ id: "cmrApi", key: "list_apis", name: "Listar APIs", module: "configuracion", submodule: "apis", active: true }],
    }),
  },
  {
    key: "toggle_api",
    name: "Activar/inhabilitar API",
    description: "Cambia el estado activo/inactivo de una API del agente.",
    module: "configuracion",
    submodule: "apis",
    category: "internal",
    method: "PATCH",
    path: "/api/config/apis/{id}/toggle",
    authType: "none",
    docs: JSON.stringify({
      params: [
        { name: "id", type: "string", in: "path", required: true },
        { name: "active", type: "boolean", in: "body", required: true },
      ],
      request: { active: false },
      response: { id: "cmrApi", key: "toggle_api", active: false },
    }),
  },
  {
    key: "list_audit",
    name: "Listar auditoría",
    description: "Devuelve los eventos de auditoría recientes de la plataforma.",
    module: "configuracion",
    submodule: "auditoria",
    category: "internal",
    method: "GET",
    path: "/api/config/audit?limit={limit}",
    authType: "none",
    docs: JSON.stringify({
      params: [{ name: "limit", type: "number", in: "query", required: false, default: 100 }],
      request: null,
      response: [{ id: "cmrLog", action: "upload_pdf", status: "success", message: "PDF procesado", createdAt: "2026-07-03T00:00:00Z" }],
    }),
  },
  {
    key: "upload_document",
    name: "Subir documento oficial",
    description: "Sube un PDF, extrae texto y genera metadatos con IA.",
    module: "base_oficial",
    submodule: "carga_documental",
    category: "internal",
    method: "POST",
    path: "/api/documents",
    authType: "none",
    docs: JSON.stringify({
      params: [
        { name: "file", type: "file", in: "formData", required: true, desc: "PDF" },
        { name: "tipo", type: "string", in: "formData", required: false, default: "otro" },
        { name: "sector", type: "string", in: "formData", required: false },
        { name: "entidad", type: "string", in: "formData", required: false },
        { name: "fechaExpedicion", type: "YYYY-MM-DD", in: "formData", required: false },
        { name: "numero", type: "string", in: "formData", required: false },
        { name: "padreId", type: "string", in: "formData", required: false },
      ],
      request: "multipart/form-data",
      response: { id: "cmrDoc", titulo: "Resolución 123", status: "completed" },
    }),
  },
  {
    key: "search_documents",
    name: "Buscar documentos",
    description: "Realiza búsqueda por términos en la base oficial.",
    module: "base_oficial",
    submodule: "busqueda_rag",
    category: "internal",
    method: "POST",
    path: "/api/documents/search",
    authType: "none",
    docs: JSON.stringify({
      params: [{ name: "query", type: "string", in: "body", required: true }],
      request: { query: "transporte público" },
      response: [{ id: "cmrDoc", titulo: "Resolución 123", score: 3, resumen: "..." }],
    }),
  },
  {
    key: "list_documents",
    name: "Listar documentos",
    description: "Devuelve todos los documentos oficiales indexados.",
    module: "base_oficial",
    submodule: "repositorio",
    category: "internal",
    method: "GET",
    path: "/api/documents",
    authType: "none",
    docs: JSON.stringify({
      params: [],
      request: null,
      response: [{ id: "cmrDoc", titulo: "Resolución 123", tipo: "resolucion", entidad: "MinTransporte" }],
    }),
  },
  {
    key: "analyze_document",
    name: "Analizar documento",
    description: "Ejecuta análisis estratégico Odin sobre un documento o texto.",
    module: "investigacion",
    submodule: "odin_analysis",
    category: "internal",
    method: "POST",
    path: "/api/research/analyze",
    authType: "none",
    docs: JSON.stringify({
      params: [
        { name: "documentId", type: "string", in: "body", required: false, desc: "ID del documento en base oficial" },
        { name: "text", type: "string", in: "body", required: false, desc: "Texto libre a analizar (alternativa a documentId)" },
      ],
      request: { text: "Texto del documento a analizar..." },
      response: { ok: true, analysis: { summary: "...", milestones: [], risks: [], recommendations: [] }, rawText: "...", latencyMs: 200, usage: {} },
    }),
  },
  {
    key: "ollama_local",
    name: "Ollama local",
    description: "API de modelos locales via Ollama.",
    module: "infraestructura",
    submodule: "modelos_locales",
    category: "external",
    method: "GET",
    path: "{baseUrl}/api/tags",
    authType: "none",
    config: JSON.stringify({ baseUrl: "http://localhost:11434" }),
    docs: JSON.stringify({
      params: [{ name: "baseUrl", type: "string", in: "config", required: false, default: "http://localhost:11434" }],
      request: null,
      response: { models: [{ name: "qwen2.5:32b" }] },
    }),
  },
  {
    key: "openai_api",
    name: "OpenAI API",
    description: "API de modelos cloud de OpenAI.",
    module: "infraestructura",
    submodule: "modelos_cloud",
    category: "external",
    method: "POST",
    path: "https://api.openai.com/v1/chat/completions",
    authType: "apiKey",
    docs: JSON.stringify({
      params: [
        { name: "Authorization", type: "Bearer token", in: "header", required: true, desc: "OPENAI_API_KEY" },
        { name: "model", type: "string", in: "body", required: true },
        { name: "messages", type: "array", in: "body", required: true },
      ],
      request: { model: "gpt-4o-mini", messages: [{ role: "user", content: "Hola" }] },
      response: { choices: [{ message: { content: "..." } }] },
    }),
  },
];

async function main() {
  await prisma.agentApi.deleteMany();
  await prisma.agentApi.createMany({ data: APIS });
  console.log(`Sembradas ${APIS.length} APIs.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
