-- SPEC-202 (002-PI-099): extiende AccionAudit con las acciones del panel admin
-- del motor de notificaciones. Migración aditiva pura (ALTER TYPE ADD VALUE IF NOT EXISTS).

ALTER TYPE "AccionAudit" ADD VALUE IF NOT EXISTS 'NOTIFICACION_REGLA_ACTUALIZADA';
ALTER TYPE "AccionAudit" ADD VALUE IF NOT EXISTS 'NOTIFICACION_PLANTILLA_ACTUALIZADA';
ALTER TYPE "AccionAudit" ADD VALUE IF NOT EXISTS 'NOTIFICACION_PARAMETRO_ACTUALIZADO';
