services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://innova:innova@db:5432/innovadataco?schema=public
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_APIKEY: ${OPENAI_APIKEY}
      OLLAMA_BASEURL: ${OLLAMA_BASEURL:-http://localhost:11434}
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: innova
      POSTGRES_PASSWORD: innova
      POSTGRES_DB: innovadataco
    ports:
      - "5432:5432"
    volumes:
      - innovadataco_db_data:/var/lib/postgresql/data

volumes:
  innovadataco_db_data: