-- SPEC-212/214: acciones de auditoría para el módulo de pagos.
-- Cambio aditivo al enum AccionAudit.

ALTER TYPE "AccionAudit" ADD VALUE 'PAGO_AUTORIZADO';
ALTER TYPE "AccionAudit" ADD VALUE 'PAGO_RECHAZADO';
ALTER TYPE "AccionAudit" ADD VALUE 'PAGO_REEMBOLSADO';
ALTER TYPE "AccionAudit" ADD VALUE 'BONO_CREADO';
ALTER TYPE "AccionAudit" ADD VALUE 'BONO_ACTUALIZADO';
ALTER TYPE "AccionAudit" ADD VALUE 'BONO_DESACTIVADO';
ALTER TYPE "AccionAudit" ADD VALUE 'PLAN_ACTUALIZADO';
ALTER TYPE "AccionAudit" ADD VALUE 'SUSCRIPCION_EXTENSION_MANUAL';
ALTER TYPE "AccionAudit" ADD VALUE 'TASA_MANUAL_CREADA';
