/**
 * Lista explícita de archivos de test considerados unitarios (sin base de datos).
 * Se usa en vitest.unit.config.ts y en el project "unit" de vitest.config.ts.
 * Mantener al día al agregar tests unitarios puros.
 */
export const UNIT_TEST_INCLUDES: string[] = [
    "prisma/seed-security.test.ts",
    "scripts/arch/no-prisma-mocks.test.ts",
    // SPEC-287 (002-PI-187): fuente única de guardias + cookie firmada de vigencia + 4 ratchets estáticos.
    "src/lib/routing/guardias.test.ts",
    "src/lib/routing/vigencia-cookie.test.ts",
    "src/lib/routing/middleware.test.ts",
    "scripts/lint/ratchets.test.ts",
    // SPEC-284 (002-PI-184 · I-130): compuerta de IDs de advisory lock únicos.
    "scripts/locks-check.test.ts",
    // SPEC-280 (002-PI-180): constructor puro del resumen del CI, sin BD ni red.
    "scripts/ci/resumen.test.mjs",
    // SPEC-281 (002-PI-180): algoritmo LPT de reparto de shards por peso.
    "scripts/ci/reparto-shards.test.mjs",
    // SPEC-290 (002-PI-190): heartbeat de vida del worker-sesiones (helper puro).
    "scripts/worker-sesiones.test.mjs",
    // SPEC-290 (002-PI-190): mapeo sesion.* → sección "sesiones" del ConfigPanel.
    "src/components/modules/config-panel/types.test.ts",
    "src/app/dashboard/admin/estadisticas/components/EstadisticasSubNav.test.tsx",
    "src/app/dashboard/colegio/alertas/AlertasColegioPageClient.test.tsx",
    "src/components/modules/config-panel/MantenimientoLogsPanel.test.tsx",
    // SPEC-241 (002-PI-144): modal de consentimiento informado (sin BD).
    "src/components/modules/ModalConsentimiento.test.tsx",
    "src/app/dashboard/colegio/cursos/CursosPageClient.test.tsx",
    "src/app/dashboard/colegio/configuracion/ConfiguracionPageClient.test.tsx",
    "src/app/dashboard/colegio/profesores/ProfesoresPageClient.test.tsx",
    "src/components/modules/AdminNav.test.tsx",
    "src/components/modules/AdminAntiAbusoSimulador.test.tsx",
    "src/components/modules/AdminAntiAbusoSimulacion.test.tsx",
    "src/components/modules/AdminReporteDetalle.test.tsx",
    "src/components/modules/AdminReporteExpediente.test.tsx",
    "src/components/modules/admin/UsuariosSubNav.test.tsx",
    "src/components/modules/admin/tables/tables.test.tsx",
    // SPEC-233: búsqueda por identificador (padre + admin)
    "src/components/modules/admin/IdentificadorAgregadoAnonimo.test.tsx",
    "src/components/modules/admin/IdentificadorExpedientesAnonimos.test.tsx",
    "src/components/modules/padre/IdentificadorBusquedaClient.test.tsx",
    "src/components/modules/ComiteBandeja.test.tsx",
    "src/components/modules/ComiteSolicitudDetalle.test.tsx",
    "src/components/modules/ConsultaEnriquecidaClient.test.tsx",
    "src/components/modules/ConsultaVaciaBloque.test.tsx",
    "src/components/modules/EstadoTransicion.test.tsx",
    "src/components/modules/LandingFooter.test.tsx",
    "src/components/modules/LandingHero.test.tsx",
    "src/components/modules/MisReporteDetalle.test.tsx",
    "src/components/modules/NavHeader.test.tsx",
    "src/components/modules/PublicDashboard.test.tsx",
    "src/components/modules/ReporteWizard.test.tsx",
    "src/components/modules/SeguimientoClient.test.tsx",
    "src/components/modules/SpamRevisionPanel.test.tsx",
    "src/components/modules/spam/SpamAnaliticaPanel.test.tsx",
    "src/components/modules/spam/SpamFiltros.test.tsx",
    "src/components/modules/spam/SpamReportesTabla.test.tsx",
    "src/components/modules/spam/SpamResolucionModal.test.tsx",
    "src/components/modules/audit-log/legible.test.ts",
    "src/components/modules/colegio/BuscadorGlobal.test.tsx",
    "src/components/modules/colegio/ColegioSideNav.test.tsx",
    "src/components/modules/colegio/comite/ComiteEstadisticas.test.tsx",
    "src/components/modules/colegio/curso/AcudienteContacto.test.tsx",
    "src/components/modules/colegio/curso/AnilloCurso.test.tsx",
    "src/components/modules/colegio/curso/CursoHeader.test.tsx",
    "src/components/modules/colegio/curso/FormAgregarEstudiante.test.tsx",
    "src/components/modules/colegio/curso/TablaEstudiantes.test.tsx",
    "src/components/modules/colegio/curso/TarjetasCurso.test.tsx",
    "src/components/modules/colegio/estadisticas/BarrasPorCurso.test.tsx",
    "src/components/modules/colegio/estadisticas/RelojActividad.test.tsx",
    "src/components/modules/colegio/estadisticas/RitmoMensual.test.tsx",
    "src/components/modules/colegio/home/AccionesRapidas.test.tsx",
    "src/components/modules/colegio/home/AnillosProteccion.test.tsx",
    "src/components/modules/colegio/home/CursosQueMerecenMirada.test.tsx",
    "src/components/modules/colegio/home/EmbudoEstado.test.tsx",
    "src/components/modules/colegio/home/EmptyStateColegio.test.tsx",
    "src/components/modules/colegio/home/FranjaVigilancia.test.tsx",
    "src/components/modules/colegio/home/HeroEstado.test.tsx",
    "src/components/modules/colegio/home/HomeRectorPage.test.tsx",
    "src/components/modules/colegio/home/TendenciaReportes.test.tsx",
    "src/components/modules/colegio/seguimiento/BitacoraCaso.test.tsx",
    "src/components/modules/colegio/seguimiento/PendientesCaso.test.tsx",
    "src/components/modules/colegio/seguimiento/TimelineCaso.test.tsx",
    "src/components/modules/colegio/unificado/ImportExcel.test.tsx",
    "src/components/modules/colegio/unificado/SeccionCurso.test.tsx",
    "src/components/modules/colegio/unificado/SeccionIdentificadores.test.tsx",
    "src/components/modules/colegio/unificado/TablaEstudiantes.test.tsx",
    "src/components/modules/colegio/unificado/WizardUnificado.test.tsx",
    "src/components/modules/ia/IaModelSelector.test.tsx",
    "src/components/modules/ia/simulacion/TablaResultadosSimulacion.test.tsx",
    "src/components/modules/monitoreo/LogContextoModal.test.tsx",
    "src/components/modules/monitoreo/LogsTab.test.tsx",
    "src/components/modules/monitoreo/OperacionTableroClient.test.tsx",
    "src/components/modules/monitoreo/SemaforoCard.test.tsx",
    "src/components/modules/operadores/ReasignarModal.test.tsx",
    "src/components/modules/motor/DerivaProdBloque.test.tsx",
    "src/components/modules/nav-logo.test.ts",
    "src/components/providers/SessionPingProvider.test.tsx",
    "src/components/ui/Accordion.test.tsx",
    "src/components/ui/Alerta.test.tsx",
    "src/components/ui/Anillo.test.tsx",
    "src/components/ui/Cargando.test.tsx",
    "src/components/ui/CiudadSearchSelect.test.tsx",
    "src/components/ui/CommandPalette.test.tsx",
    "src/components/ui/Declaracion.test.tsx",
    "src/components/ui/EmptyState.test.tsx",
    "src/components/ui/ErrorState.test.tsx",
    "src/components/ui/LuzAmbiental.test.tsx",
    "src/components/ui/Modal.test.tsx",
    "src/components/ui/PanelVidrio.test.tsx",
    "src/components/ui/Tabla.test.tsx",
    "src/components/ui/TarjetaMetrica.test.tsx",
    "src/components/ui/Textarea.test.tsx",
    "src/components/ui/Tooltip.test.tsx",
    "src/components/ui/use-fetch-json.test.tsx",
    "src/lib/ai/anonimizador.test.ts",
    "src/lib/ai/classifier-votos.test.ts",
    "src/lib/ai/classifier.test.ts",
    "src/lib/ai/eval-runner.test.ts",
    "src/lib/ai/guardas-decision.test.ts",
    "src/lib/ai/keywords-riesgo.test.ts",
    "src/lib/ai/ollama-config.test.ts",
    "src/lib/ai/pii-patterns.test.ts",
    "src/lib/ai/rubrica-config.test.ts",
    "src/lib/ai/rubrica.test.ts",
    // SPEC-220: helpers puros de períodos Bogotá del dominio Análisis.
    "src/lib/analisis/periodos.test.ts",
    // SPEC-221 (002-PI-122): validador SQL y renderer de plantillas del motor de reglas (puros).
    "src/lib/analisis/reglas/ejecutor-sql.test.ts",
    "src/lib/analisis/reglas/plantilla.test.ts",
    // SPEC-223: ventana semanal Bogotá/ISO y contenido puro del digest (sin BD).
    "src/lib/analisis/semana.test.ts",
    "src/lib/analisis/digest-contenido.test.ts",
    // SPEC-225 (002-PI-126): ventanas Bogotá, comparativa semanal y puntualidad del detector (puros).
    "src/lib/analisis/anomalias/ventanas.test.ts",
    "src/lib/analisis/anomalias/comparativas.test.ts",
    "src/lib/analisis/anomalias/puntualidad.test.ts",
    // SPEC-225 (002-PI-126): fail-open de alertas al CEO (Motor Notif mockeado, sin BD).
    "src/lib/analisis/anomalias/alertas.test.ts",
    // SPEC-220: card presentacional del score de valor (sin BD).
    "src/components/modules/pagos/ScoreClienteCard.test.tsx",
    // SPEC-245 (002-PI-148): modal de activación / autorización manual (sin BD).
    "src/components/modules/pagos/ActivarSuscripcionManual.test.tsx",
    // 002-PI-068: fuente-reporte-salt.test.ts importa fuente-reporte.ts que carga
    // repositorios Prisma al evaluarse; lo movemos a integration.
    "src/lib/api-handler.test.ts",
    "src/lib/auth.test.ts",
    "src/lib/colegio/alertas-prioridad.test.ts",
    // 002-PI-068: parser.test.ts importa parser.ts que carga repositorios Prisma.
    "src/lib/colegio/carga/validator.test.ts",
    "src/lib/dal/repositories/analytics-colegio-helpers.test.ts",
    "src/lib/colegio/fechas-humano.test.ts",
    "src/lib/colegio/normalizacion.test.ts",
    "src/lib/colegio/periodo.test.ts",
    "src/lib/colegio/seguimiento.test.ts",
    "src/lib/colegio/semaforo.test.ts",
    "src/lib/config-cache.test.ts",
    "src/lib/credenciales-literal.test.ts",
    "src/lib/design-tokens.test.ts",
    "src/lib/docs/indice.test.ts",
    "src/lib/errors.test.ts",
    "src/lib/expediente/analisis-interno.test.ts",
    "src/lib/expediente/expediente-forense.test.ts",
    // SPEC-236: whitelist pura de la máquina de estados (sin BD).
    "src/lib/expediente/estados/transiciones.test.ts",
    "src/lib/expediente/mensaje-padre.test.ts",
    // SPEC-236: helpers puros de fechas del motor (America/Bogota, sin BD).
    "src/lib/expediente/motor/fechas-motor.test.ts",
    "src/lib/expediente/pdf-denuncia.test.ts",
    "src/lib/fetch-retry.test.ts",
    "src/lib/format/fecha.test.ts",
    "src/lib/ai/sandbox.test.ts",
    "src/lib/monitoreo/worker-logger.test.ts",
    "src/lib/monitoreo/tick-vida.test.ts",
    "src/lib/servicios/docker-adapter.test.ts",
    "src/lib/servicios/compose.ratchet.test.ts",
    "src/lib/servicios/tick-vida.ratchet.test.ts",
    "src/lib/servicios/api-guard.ratchet.test.ts",
    "src/lib/dal/services/session-log.unit.test.ts",
    "src/hooks/useSessionPing.test.ts",
    "src/lib/session-log/ip-hash.test.ts",
    "src/lib/nav-items.test.ts",
    "src/lib/normalizar.test.ts",
    "src/lib/notificaciones/offset.test.ts",
    "src/lib/notificaciones/quiet-hours.test.ts",
    "src/lib/notificaciones/renderer.test.ts",
    // SPEC-302 (002-PI-208): logger estructurado del motor — todo mockeado, sin BD.
    "src/lib/notificaciones/motor-logger.test.ts",
    "src/lib/param-encryption.test.ts",
    "src/lib/pagos/api-helpers.test.ts",
    "src/lib/pagos/bono-aplicacion.service.test.ts",
    "src/lib/pagos/pagos-calculos.service.test.ts",
    "src/lib/pagos/tasas.test.ts",
    // SPEC-213 (002-PI-113): motor de vigencia de pagos.
    "src/lib/pagos/vigencia.service.test.ts",
    // SPEC-211 (002-PI-111): vistas de cliente del módulo de pagos.
    "src/lib/pagos/renovacion-calculos.test.ts",
    // SPEC-215 (002-PI-115): generador puro de códigos de referido (sin BD).
    "src/lib/utils/referido-codigo.test.ts",
    "src/lib/pagos/comprobante-storage.test.ts",
    "src/components/modules/cliente/suscripcion/SuscripcionResumen.test.tsx",
    // SPEC-218 (002-PI-118): analítica dinero-vs-valor (cálculos puros, servicio con repo doble y componentes).
    "src/lib/pagos/analitica-calculos.test.ts",
    "src/lib/pagos/analitica.service.test.ts",
    "src/components/modules/admin/pagos/analitica/KpiPagosCards.test.tsx",
    "src/components/modules/admin/pagos/analitica/WidgetsAccion.test.tsx",
    "src/components/modules/admin/pagos/analitica/WidgetCrecimientoPaisCiudad.test.tsx",
    // SPEC-217 (002-PI-117): freemium 30 días (cálculos puros y servicio con dependencias mockeadas, sin BD).
    "src/lib/pagos/freemium-calculos.test.ts",
    "src/lib/pagos/freemium.service.test.ts",
    "src/lib/plataforma.test.ts",
    "src/lib/proxy.test.ts",
    "src/lib/queue.test.ts",
    "src/lib/reporte-aprobado.test.ts",
    "src/lib/reporte-estados-usuario.test.ts",
    "src/lib/reportes-acceso.test.ts",
    "src/lib/riesgo-consulta.test.ts",
    // 002-PI-068: role-visibility.test.tsx importa proxy.ts que carga repositorios Prisma.
    "src/lib/schemas/index.test.ts",
    "src/lib/schemas/pagos.test.ts",
    "src/lib/schemas/unificado.test.ts",
    "src/lib/simulacion/executor.test.ts",
    "src/lib/simulacion/metricas.test.ts",
    "src/lib/simulacion/parser.test.ts",
    "src/lib/simulacion/progreso.test.ts",
    "src/lib/specs-discipline.test.ts",
    "src/lib/texto-reporte-cifrado.test.ts",
    "src/lib/texto-reporte-frontera.test.ts",
    "src/lib/url-privacy.test.ts",
    "src/lib/validation.test.ts",
    "src/lib/validators.test.ts",
    "src/lib/version.test.ts",
    "src/lib/worker-auth.test.ts",
    "src/lib/worker-heartbeat.test.ts",
    "src/proxy-csp.test.ts",
    // SPEC-237: bandeja comité CONSOLIDACION + aprobación multi-miembro
    "src/lib/comite/sla.test.ts",
    "src/components/modules/comite/consolidacion/ConsolidacionAcciones.test.tsx",
    // SPEC-222: helpers puros y schemas Zod del panel Dinero vs Valor.
    "src/lib/analisis/panel-calculos.test.ts",
    "src/lib/schemas/analisis-panel.test.ts",
    // SPEC-238: helpers puros del SLA de aclaración y schemas Zod (sin BD).
    "src/lib/expediente/motor/sla-aclaracion.test.ts",
    "src/lib/schemas/aclaracion.test.ts",
    // SPEC-222: bloque Top 5 decisiones del panel (sin BD).
    "src/app/dashboard/admin/estadisticas/dinero-vs-valor/components/TopDecisiones.test.tsx",
    // SPEC-239: schemas Zod de contactos de emergencia y botón de emergencia del comité (sin BD).
    "src/lib/schemas/contacto-emergencia.test.ts",
    "src/components/modules/comite/consolidacion/BotonActivarEmergencia.test.tsx",
    // SPEC-227: filtros Zod + pseudonimización + CSV + vista del historial (sin BD).
    "src/lib/analisis/filtros-historial.test.ts",
    "src/lib/analisis/pseudonimizar.test.ts",
    "src/lib/analisis/historial-csv.test.ts",
    "src/app/dashboard/admin/analisis/recomendaciones/components/HistorialRecomendaciones.test.tsx",
    // SPEC-224: validador estático SQL, helpers del test-sql, versionado y schemas Zod (sin BD).
    "src/lib/analisis/reglas/validar-sql.test.ts",
    "src/lib/analisis/reglas/test-sql.test.ts",
    "src/lib/analisis/reglas/versionado.test.ts",
    "src/lib/schemas/analisis-reglas.test.ts",
    // SPEC-224: diálogo de confirmación fuerte del cambio de modo (fetch mockeado, sin BD).
    "src/components/modules/analisis/ReglaModoDialog.test.tsx",
    // SPEC-226: schemas Zod de acciones + helpers puros de handlers (vigencia Bogotá, nombre bono, destinatarios alerta, menor_carga).
    "src/lib/analisis/acciones/schemas.test.ts",
    "src/lib/analisis/acciones/handlers/crear-bono.test.ts",
    "src/lib/analisis/acciones/handlers/crear-alerta.test.ts",
    "src/lib/analisis/acciones/handlers/asignar-operador.test.ts",
    // SPEC-240 (002-PI-143): pre-registro simplificado de colegio (sin BD).
    "src/app/dashboard/admin/colegios/nuevo/NuevoColegioPageClient.test.tsx",
    "src/components/modules/InvitacionEnviadaModal.test.tsx",
];
