slice_name: 7 · Reintentos Reporte 24 h fallidos
viz_type: big_number_total
uuid: 7d049ee9-da85-5166-8a07-1d10a0f14877
version: 1.0.0
dataset_uuid: fa73218e-3e08-5ea0-8f24-e24263737312
description: Chart del dashboard 'salud' · fuente SQL en spec.md.
certified_by: Fábrica BI-2
certification_details: Aprobado en compuerta §4 · SPEC-019..023 · F3C 2026-08-29
params:
  viz_type: big_number_total
  adhoc_filters: []
  extra_form_data: {}
  dashboards: []
  metric:
    expressionType: SQL
    sqlExpression: "SELECT count(*) FROM \"ReintentoReporte\" WHERE \"creadoEn\" >= NOW() - INTERVAL '24 hours' AND exitoso = false"
    label: valor
    hasCustomLabel: true
query_context: "{\"datasource\": {\"uuid\": \"fa73218e-3e08-5ea0-8f24-e24263737312\", \"type\": \"table\"}, \"force\": false, \"queries\": [{\"custom_form_data\": {}, \"extras\": {\"having\": \"\", \"where\": \"\"}, \"annotation_layers\": [], \"row_limit\": 10000, \"orderby\": [], \"sql\": \"SELECT count(*) FROM \\\"ReintentoReporte\\\" WHERE \\\"creadoEn\\\" >= NOW() - INTERVAL '24 hours' AND exitoso = false\"}], \"result_format\": \"json\", \"result_type\": \"full\"}"
cache_timeout: 1800
is_managed_externally: true
external_url: null
tags:
  - bi-mvp
  - salud
