export const ENTIDADES_COLOMBIA = [
  "Congreso de la República",
  "Presidencia de la República",
  "Ministerio del Interior",
  "Ministerio de Relaciones Exteriores",
  "Ministerio de Hacienda y Crédito Público",
  "Ministerio de Justicia y del Derecho",
  "Ministerio de Defensa Nacional",
  "Ministerio de Agricultura y Desarrollo Rural",
  "Ministerio de Salud y Protección Social",
  "Ministerio de Trabajo",
  "Ministerio de Educación Nacional",
  "Ministerio de Ambiente y Desarrollo Sostenible",
  "Ministerio de Vivienda, Ciudad y Territorio",
  "Ministerio de Transporte",
  "Ministerio de Tecnologías de la Información y las Comunicaciones",
  "Ministerio de Cultura",
  "Ministerio de Comercio, Industria y Turismo",
  "Ministerio de Minas y Energía",
  "Ministerio de Inclusión Social",
  "Ministerio de Ciencia, Tecnología e Innovación",
  "Departamento Nacional de Planeación",
  "Dirección de Impuestos y Aduanas Nacionales - DIAN",
  "Instituto Colombiano de Bienestar Familiar - ICBF",
  "Servicio Nacional de Aprendizaje - SENA",
  "Instituto Colombiano para el Fomento de la Educación Superior - ICFES",
  "Fondo Nacional de Salud - FONSALUD",
  "Agencia Nacional de Licencias Ambientales - ANLA",
  "Unidad Nacional de Protección",
  "Agencia Nacional de Seguridad Vial",
  "Superintendencia de Industria y Comercio",
  "Superintendencia Financiera de Colombia",
  "Superintendencia de Salud",
  "Superintendencia de Vigilancia y Seguridad Privada",
  "Contraloría General de la República",
  "Procuraduría General de la Nación",
  "Defensoría del Pueblo",
  "Registraduría Nacional del Estado Civil",
  "Consejo Nacional Electoral",
  "Jurisdicción Especial para la Paz",
  "Agencia Nacional de Infraestructura",
  "Fondo de Adaptación",
  "Banco de la República",
  "Fondo de Pensiones del Magisterio",
  "Colpensiones",
  "INVIAS",
  "ANI",
  "Fondo Nacional de Regalías",
  "Entidad Territorial - Alcaldía",
  "Entidad Territorial - Gobernación",
  "Entidad Territorial - Concejo Municipal",
  "Entidad Territorial - Asamblea Departamental",
  "Otra",
];
