export const ENTIDADES_COLOMBIA = [
  "Congreso de la Rep\u00fablica",
  "Presidencia de la Rep\u00fablica",
  "Ministerio del Interior",
  "Ministerio de Relaciones Exteriores",
  "Ministerio de Hacienda y Cr\u00e9dito P\u00fablico",
  "Ministerio de Justicia y del Derecho",
  "Ministerio de Defensa Nacional",
  "Ministerio de Agricultura y Desarrollo Rural",
  "Ministerio de Salud y Protecci\u00f3n Social",
  "Ministerio de Trabajo",
  "Ministerio de Educaci\u00f3n Nacional",
  "Ministerio de Ambiente y Desarrollo Sostenible",
  "Ministerio de Vivienda, Ciudad y Territorio",
  "Ministerio de Transporte",
  "Ministerio de Tecnolog\u00edas de la Informaci\u00f3n y las Comunicaciones",
  "Ministerio de Cultura",
  "Ministerio de Comercio, Industria y Turismo",
  "Ministerio de Minas y Energ\u00eda",
  "Ministerio de Inclusi\u00f3n Social",
  "Ministerio de Ciencia, Tecnolog\u00eda e Innovaci\u00f3n",
  "Departamento Nacional de Planeaci\u00f3n",
  "Direcci\u00f3n de Impuestos y Aduanas Nacionales - DIAN",
  "Instituto Colombiano de Bienestar Familiar - ICBF",
  "Servicio Nacional de Aprendizaje - SENA",
  "Instituto Colombiano para el Fomento de la Educaci\u00f3n Superior - ICFES",
  "Fondo Nacional de Salud - FONSALUD",
  "Agencia Nacional de Licencias Ambientales - ANLA",
  "Unidad Nacional de Protecci\u00f3n",
  "Agencia Nacional de Seguridad Vial",
  "Superintendencia de Industria y Comercio",
  "Superintendencia Financiera de Colombia",
  "Superintendencia de Salud",
  "Superintendencia de Vigilancia y Seguridad Privada",
  "Contralor\u00eda General de la Rep\u00fablica",
  "Procuradur\u00eda General de la Naci\u00f3n",
  "Defensor\u00eda del Pueblo",
  "Registradur\u00eda Nacional del Estado Civil",
  "Consejo Nacional Electoral",
  "Jurisdicci\u00f3n Especial para la Paz",
  "Agencia Nacional de Infraestructura",
  "Fondo de Adaptaci\u00f3n",
  "Banco de la Rep\u00fablica",
  "Fondo de Pensiones del Magisterio",
  "Colpensiones",
  "INVIAS",
  "ANI",
  "Fondo Nacional de Regal\u00edas",
  "Entidad Territorial - Alcald\u00eda",
  "Entidad Territorial - Gobernaci\u00f3n",
  "Entidad Territorial - Concejo Municipal",
  "Entidad Territorial - Asamblea Departamental",
  "Otra",
];
