export const SECTORES_COLOMBIA = [
  "Transporte",
  "Minas y Energía",
  "Tecnologías de la Información y las Comunicaciones - TIC",
  "Salud",
  "Educación",
  "Seguridad y Defensa",
  "Hacienda y Crédito Público",
  "Justicia y Derecho",
  "Agricultura y Desarrollo Rural",
  "Ambiente y Desarrollo Sostenible",
  "Vivienda, Ciudad y Territorio",
  "Trabajo",
  "Comercio, Industria y Turismo",
  "Cultura",
  "Inclusión Social",
  "Ciencia, Tecnología e Innovación",
  "Planeación",
  "Deporte",
  "Gobierno Digital",
  "Regulación Financiera",
  "Transparencia y Control",
  "Otro",
];
