export const SECTORES_COLOMBIA = [
  "Transporte",
  "Minas y Energ\u00eda",
  "Tecnolog\u00edas de la Informaci\u00f3n y las Comunicaciones - TIC",
  "Salud",
  "Educaci\u00f3n",
  "Seguridad y Defensa",
  "Hacienda y Cr\u00e9dito P\u00fablico",
  "Justicia y Derecho",
  "Agricultura y Desarrollo Rural",
  "Ambiente y Desarrollo Sostenible",
  "Vivienda, Ciudad y Territorio",
  "Trabajo",
  "Comercio, Industria y Turismo",
  "Cultura",
  "Inclusi\u00f3n Social",
  "Ciencia, Tecnolog\u00eda e Innovaci\u00f3n",
  "Planeaci\u00f3n",
  "Deporte",
  "Gobierno Digital",
  "Regulaci\u00f3n Financiera",
  "Transparencia y Control",
  "Otro",
];
