-- SPEC-162: extiende el enum de auditoría con las acciones del catálogo
-- de materias y del vínculo Curso × Materia. Migración aditiva (ALTER TYPE ADD VALUE).
ALTER TYPE "AccionAudit" ADD VALUE 'COLEGIO_MATERIA_CREADA';
ALTER TYPE "AccionAudit" ADD VALUE 'COLEGIO_MATERIA_EDITADA';
ALTER TYPE "AccionAudit" ADD VALUE 'COLEGIO_MATERIA_DESACTIVADA';
ALTER TYPE "AccionAudit" ADD VALUE 'COLEGIO_MATERIA_REACTIVADA';
ALTER TYPE "AccionAudit" ADD VALUE 'COLEGIO_CURSO_MATERIA_CREADA';
ALTER TYPE "AccionAudit" ADD VALUE 'COLEGIO_CURSO_MATERIA_DESACTIVADA';
